# Generated by Django 4.1.7 on 2024-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_city_alter_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Nairobi", max_length=180, verbose_name="city"
            ),
        ),
    ]
